### ISSUE TITLE
Diving deeper into OKM search results

### ISSUE THREAD

**Issue by Bubblbu** [OpenKnowledgeMaps/Headstart#129]
# Diving deeper into OKM search results

A simple approach to enable a "layered" approach to discovering more literature based on the results of an initial search.

## Example

1. Initial user query: *"cancer"* ([Resulting map](https://openknowledgemaps.org/vis.php?id=3d36c26c9ebe63706a7657104fbd3cec&query=cancer&service=pubmed))
   User is interested in the biggest bubble which is *"Surveillance, Epidemiology, Human papillomavirus vaccines"* and decides to look at the Knowledge Map of this topic itself.
2. Dive into the topic ([Resulting map](https://openknowledgemaps.org/vis.php?id=90501df514ca4deb1bb77c6e269c029a&query=surveillance%20or%20epidemiology%20or%20human%20papillomavirus%20vaccines&service=pubmed))
    We automatically redirect to a new map and present the results for *"surveillance or epidemiology or human papillomavirus vaccines"*. 
3. Repeat
4. Win

## To-do

- [ ] Add user interface to expand a bubble (button?)
- [ ] Evaluate best way to construct new query from the given three keywords. (e.g., "key1 OR key2 OR key3")
- [ ] Redirect to new map on click
